// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ChatGpt: typeof import('./components/drawer/chatGpt.vue')['default']
    'ChatGpt copy': typeof import('./components/drawer/chatGpt copy.vue')['default']
    Drawer: typeof import('./components/drawer/drawer.vue')['default']
    Search: typeof import('./components/section/search.vue')['default']
    Section: typeof import('./components/section/section.vue')['default']
    Time: typeof import('./components/time/time.vue')['default']
  }
}

export {}
